### ISSUE TITLE
Guess Number upgrade 

### ISSUE THREAD

**Issue by ndkazu** [Phala-Network/bounty-program#1]
Upgrade of the guess number game by adding a bot as an adversary, a way to track the score of both players
- https://github.com/ndkazu/guessNumber-vs-Bot
- https://github.com/ndkazu/js-sdk-for-guessNumber_Bot

**Comment by h4x3rotab** [comment]
Already paid!

https://www.subsquare.io/khala/treasury/tip/702919_0x5dd557a4d45fd186b9b1f38d10d620635d691cdb5fbe17ddb5e45e866eed3cd1
